import { PositionRecord } from './types';

export const DEFAULT_SOLANA_POSITIONS: PositionRecord[] = [
  {
    id: 'pos-kamino-sol-01',
    agent_id: 'agent-eliza-sol-01',
    user_id: 'user-01',
    protocol_slug: 'kamino',
    position_type: 'lend',
    asset: 'SOL',
    amount: 1450,
    amount_usd: 268250,
    entry_price: 175.2,
    current_price: 185.0,
    health_factor: 1.68,
    liquidation_price: 122.4,
    pnl_usd: 14210,
    status: 'open',
    last_checked: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pos-drift-sol-02',
    agent_id: 'agent-sol-kit-02',
    user_id: 'user-01',
    protocol_slug: 'drift',
    position_type: 'perp',
    asset: 'SOL-PERP',
    amount: 850,
    amount_usd: 157250,
    entry_price: 178.5,
    current_price: 185.0,
    health_factor: 1.12,
    liquidation_price: 172.1,
    pnl_usd: 5525,
    status: 'open',
    last_checked: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pos-jupiter-lp-03',
    agent_id: 'agent-claude-03',
    user_id: 'user-01',
    protocol_slug: 'jupiter',
    position_type: 'lp',
    asset: 'JUP-SOL-LP',
    amount: 3200,
    amount_usd: 84200,
    entry_price: 24.5,
    current_price: 26.3,
    health_factor: 2.15,
    liquidation_price: 0,
    pnl_usd: 5760,
    status: 'open',
    last_checked: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'pos-pumpfun-bc-04',
    agent_id: 'agent-degen-04',
    user_id: 'user-01',
    protocol_slug: 'pumpfun',
    position_type: 'bonding_curve',
    asset: 'AI-MEME-SOL',
    amount: 450000,
    amount_usd: 48500,
    entry_price: 0.08,
    current_price: 0.107,
    health_factor: 1.85,
    liquidation_price: 0,
    pnl_usd: 12150,
    status: 'open',
    last_checked: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
