import { AgentRecord } from './types';

export const DEFAULT_SOLANA_AGENTS: AgentRecord[] = [
  {
    id: 'ag_eliza_sol_01',
    user_id: 'user_01',
    name: 'ElizaOS DeFi Agent',
    description: 'Autonomous yield optimization and lending rebalancer on Kamino and Solend.',
    agent_type: 'eliza',
    wallet_address: '7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ag_sol_kit_02',
    user_id: 'user_01',
    name: 'Solana Agent Kit Trading Bot',
    description: 'High frequency perp trading agent executing position guardrails on Drift Protocol.',
    agent_type: 'solana_agent_kit',
    wallet_address: '9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ag_degen_pump_03',
    user_id: 'user_01',
    name: 'Pump.fun Bonding Curve Trader',
    description: 'Automated memecoin launchpad scanner and liquidity arbitrage agent.',
    agent_type: 'custom',
    wallet_address: '3g135v1F6P1m6yM268297z2418Nwu78hRvfCKubJ14M5',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'ag_claude_lp_04',
    user_id: 'user_01',
    name: 'Claude Dynamic Liquidity Agent',
    description: 'Concentrated liquidity provider on Meteora DLMM and Jupiter pools.',
    agent_type: 'claude',
    wallet_address: '5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
